# Generated by Django 3.2.3 on 2025-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 10:00:00'),
            preserve_default=False,
        ),
    ]
